name: AaronAmsterdam
favicon: null
layout_spectrum: 0.66423
typography_spectrum: 0.13184076617471874
title: Apollo 24 Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#3a3a3a'
    - '#ffffff'
    - '#a6a6a6'
    - '#d5d5d5'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.25801529362797737
purpose: []
