title: Apollo 24 Inc.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.3960573
  rhythmicContrast: 0.4641577
  brandColors:
    - '#1a1a1a'
    - '#3a3a3a'
    - '#ffffff'
    - '#a6a6a6'
    - '#d5d5d5'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: AaronAmsterdam
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6236559
layout_spectrum: 0.6021506
