name: AaronAmsterdam
favicon: null
layout_spectrum: 0.8207885
typography_spectrum: 0.5376344
title: 'welcome!'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#3a3a3a'
    - '#ffffff'
    - '#a6a6a6'
    - '#d5d5d5'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
