name: AaronAmsterdam
favicon: null
layout_spectrum: 0.7046606601215899
typography_spectrum: 0.13184076617471874
title: Apollo 24 Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.23456232552416623
  lightness: 0.11702774651348591
  saturation: 0.36552959494292736
  rhythmicContrast: 0.25801529362797737
purpose: []
